# import the numpy library...
import numpy as np

a = np.array([ [10, 4, 7], [0, 5, 3], [2, 9, 7] ])
b = np.array([ [1, 4, 1], [1, 8, 3], [0, 4, 2]])
print("a = \n%s\n" % a)
print("b = \n%s\n" % b)

listOfLists = [ [1, 9, 3], [2, 8, 6], [7, 1, 0] ]

# convert listOfLists to a numpy matrix and print it...
# code goes here...

# turn listOfLists back into a regular python list and print it...
# code goes here...

# print the sum of all of the elements in a...
# code goes here...

# print the min of all of the elements in a...
# code goes here...

# print the max of all of the elements in a...
# code goes here...

# print the sum of the elements in each column in a...
# code goes here...

# print the sum of the elements in each row in a...
# code goes here...

# print a - b
# code goes here...

# print a squared
# code goes here...

# print a/2
# code goes here...

# print a > 2
# code goes here...

# print a * b
# code goes here...

# print the element in the first row and second column of a
# code goes here...

# print the first two rows in a
# code goes here...

# print the last two columns in a
# code goes here...

# print the intersection of the first two columns and the
# first two rows in a, HINT: this should be the following 2x2 matrix:
# 10 4
# 0 5
# code goes here...
